version: "2"

services:
  mongodb:
    container_name: mongo-local-bloggy
    image: mongo:4.1
    ports:
      - "27016:27017"
    restart: always

  bloggy-backend:
    container_name: bloggy-backend-solo
    restart: always
    command: npm run start
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app/
    ports:
      - "3000:3000"
      - "9228:9229"
